### PR TITLE
Update to MSAL 4.30.

### PR DESCRIPTION
**Pull request by pmaytak**

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM.
Thanks @pmaytak 

Should we remove the App token cache, given the default implementation?
https://github.com/Azure-Samples/ms-identity-aspnet-daemon-webapp/blob/421b8566ef6af8c4a7e2bc74bf10f33a4ea1c318/UserSync/Utils/MSALAppTokenMemoryCache.cs

cc:@bgavrilMS ?

**Review by jmprieur — COMMENTED** [review]
Should we remove the App token cache, given the default implementation?
https://github.com/Azure-Samples/ms-identity-aspnet-daemon-webapp/blob/421b8566ef6af8c4a7e2bc74bf10f33a4ea1c318/UserSync/Utils/MSALAppTokenMemoryCache.cs

cc:@bgavrilMS ?

**Comment by bgavrilMS** [comment]
Yes, if cca is singleton, we can use in the box cache.

**Comment by pmaytak** [comment]
Currently, CCA instance is not singleton; it's created for each request. But I can refactor and cleanup the sample to make it singleton.

**Comment by jmprieur** [comment]
No, let's not have a singleton. One CCA per request is the recommended way.
This sample is a bit particular it uses client credentials, but not only. See https://github.com/Azure-Samples/ms-identity-aspnet-daemon-webapp#scenario

**Pull request merged**
